export const SERVICE_THEMES = [
  {
    id: "01",
    title: "Framework",
    desc: "React, Vue2 등 프레임워크를 활용한 컴포넌트 기반 UI 개발",
    tags: [
      "React",
      "Vue2",
      "Pug",
      "TypeScript",
      "JavaScript",
      "Gulp",
      "SCSS",
      "Chart.js",
      "GitHub",
    ],
    color: "#DDD",
    projects: [
      "SK렌터카 다이렉트 1.5 구축",
      "미디어로그 기업형 메시지(RCS) 리뉴얼",
      "LG전자 글로벌 페이지 운영",
    ],
  },
  {
    id: "02",
    title: "Build",
    desc: "모바일 웹·앱 구축 및 반응형 페이지 리뉴얼 프로젝트",
    tags: ["HTML5", "CSS3", "Zeplin", "Figma", "GitLab"],
    color: "#CCC",
    projects: [
      "미래에셋 헬스케어앱 구축",
      "현대N브랜드 리뉴얼",
      "현대카드 법인 모바일 리뉴얼",
    ],
  },
  {
    id: "03",
    title: "Operation",
    desc: "반응형·적응형 홈페이지 유지보수",
    tags: [
      "Maintenance",
      "Accessibility",
      "jQuery",
      "JavaScript",
      "Photoshop",
      "GitHub",
    ],
    color: "#DDD",
    projects: [
      "SK렌터카 전사 사이트 운영",
      "LG전자 웹접근성 진단",
      "LG전자 컨텐츠 운영",
      "아모레퍼시픽 사이트 운영",
    ],
  },
];

export const ALL_PROJECTS = [
  {
    id: 9,
    title: "SK렌터카 다이렉트 1.5 구축 및 전사 사이트 운영",
    period: "2025.02 ~ 현재",
    tech: [
      "React",
      "SCSS",
      "JavaScript",
      "TypeScript",
      "Github",
      "Jira",
      "Confulance",
      "Figma",
    ],
    category: "Framework",
  },
  {
    id: 8,
    title: "LG전자 웹접근성 진단",
    period: "2025.01 ~ 2025.02",
    tech: ["HTML5", "CSS", "jQuery", "웹접근성"],
    category: "Operation",
  },
  {
    id: 7,
    title: "미래에셋 생명 헬스케어앱 구축",
    period: "2024.07 ~ 2024.12",
    tech: ["HTML5", "SCSS", "JavaScript", "Github", "Jira"],
    category: "Build",
  },
  {
    id: 6,
    title: "현대N브랜드 페이지 리뉴얼",
    period: "2024.04 ~ 2024.06",
    tech: ["HTML5", "CSS", "JavaScript", "Github", "Figma"],
    category: "Build",
  },
  {
    id: 5,
    title: "LG전자 글로벌 페이지 운영",
    period: "2023.10 ~ 2024.05",
    tech: ["GULP", "PUG", "SCSS", "GitLab", "Figma"],
    category: "Build",
  },
  {
    id: 4,
    title: "미디어로그 기업형 메시지(RCS) 리뉴얼",
    period: "2023.05 ~ 2023.10",
    tech: [
      "VUE2",
      "SCSS",
      "JavaScript",
      "ChartJs",
      "Git Lab",
      "Figma",
      "Redmine",
    ],
    category: "Framework",
  },
  {
    id: 3,
    title: "LG전자 컨텐츠 운영",
    period: "2022.06 ~ 2023.04",
    tech: ["HTML5", "CSS", "jQuery", "Photoshop"],
    category: "Operation",
  },
  {
    id: 2,
    title: "현대카드 법인 모바일 리뉴얼",
    period: "2022.03 ~ 2022.06",
    tech: ["HTML5", "CSS", "jQuery", "SVN", "Jira", "Redmine", "Zeplin"],
    category: "Build",
  },
  {
    id: 1,
    title: "아모레퍼시픽 사이트 운영",
    period: "2022.01 ~ 2022.02",
    tech: ["HTML5", "CSS", "jQuery", "Photoshop"],
    category: "Operation",
  },
];
